### ISSUE TITLE
Unzip all the files to the folder "AVA_dataset"¶

### ISSUE THREAD

**Issue by seyeeet** [niu-haoran/FLIVE_Database#3]
can you explain how you do that in ubuntu terminal?
I have difficulty make that work
![image](https://user-images.githubusercontent.com/62394093/98875257-d2a25a80-2449-11eb-90fd-4a9b09780f30.png)

**Comment by ciwei123** [comment]
@seyeeet Could you share the dataset? Thank you very much!!
