### ISSUE TITLE
为什么不直接公布整理好的数据集，造数据集搞得人头疼

### ISSUE THREAD

**Issue by Eradictor** [niu-haoran/FLIVE_Database#5]
先要下载三十多G的AVA，又要用一个奇怪的download函数下载emotic数据集，麻烦无比，现在还不知道怎么Python翻墙运行这个代码。
论文和网站做的挺漂亮，也请用心做一下数据集，谢谢。

**Comment by ciwei123** [comment]
@Eradictor 您好，请问您获取到数据集了吗，可以百度云分享下吗，我这边下载不了。非常感谢！！
